name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Remove unnecessary files
        run: |
          rm -r .github .git .gitattributes .gitignore LICENSE README.md package.json package-lock.json tsconfig.json 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./

      - name: Package files
        run: |
          zip -r package.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: package.zip
          tag: ${{ github.ref }}
          title: ${{ github.ref }}
          body: ${{ github.ref }}