name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: |
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: script.js
          path: ./out.cjs
